### ISSUE TITLE
Stats tab missing from Loadout view

### ISSUE THREAD

**Issue by JPZV** [quickkennedy/cutehud#13]
I cannot find the Stats view when I'm on my loadout.

This is what I'm specting:

![image](https://user-images.githubusercontent.com/38300410/206926411-714687f8-43c1-4454-9590-d5557d16b114.png)

And this is how it looks with Cutehud:

![image](https://user-images.githubusercontent.com/38300410/206926429-03be405c-a913-42f9-b1c5-05f680d70cb6.png)

Note the "**Loadout** Stats" at the top left corner.

**Comment by quickkennedy** [comment]
This is intentional, however this may be added down the line as a customization. For me, my stats are not representative of my true hours and as such I removed them. I am sure other people want to view them, so the work may be put in some day to view them.

**Comment by JPZV** [comment]
That could be great. Like you, the total hours doesn't representate my true hours, but for me, that screen helps me to know which classes I barely use.

If you could add it as a customization someday it'll be great as I cannot find the file nor the element where it was hidden from the hud

**Comment by quickkennedy** [comment]
implimented.
